(function(G,r){function p(a,b){var c="";b=b?b+"_":"";var e=0,d;for(d in a)if(a.hasOwnProperty(d)){0<e&&(c+="&");switch(typeof a[d]){case "object":if("Array"===a[d].constructor)for(var g=0;g<a[d].length;g++)c+=encodeURIComponent(d+"[]")+"="+encodeURIComponent(Object[d][e]);else c+=p(a[d],d);break;case "function":break;default:c+=encodeURIComponent(b+d)+"="+encodeURIComponent(a[d])}e++}return c}function t(a,d,c){var e="none-";d&&(e=d+"-");var f=e+a.r,g;window.XMLHttpRequest?g=new XMLHttpRequest:(g=
new ActiveXObject("Microsoft.XMLHTTP"),g.F(2,13056));g.open("POST",b.i+"?r="+Math.random(),c);g.setRequestHeader("Content-type","application/x-www-form-urlencoded; charset=UTF-8");c&&(b.b[f]=a,g.onreadystatechange=function(){4==g.readyState&&delete b.b[f]});g.send(p(a))}function q(a,d){150<A++&&36E5<(new Date).getTime()-B&&window.location.reload(!1);d&&(a.a=d);var c,e=new Date;c=new Date((new Date(e)).toISOString());c=new Date(c.getTime()-6E4*e.getTimezoneOffset());e=e.getTime()/1E3;e=parseInt((Math.round(1E3*
(e-parseInt(e,10)))/1E3).toString().substring(2));10>e&&(e*=100);100>e&&(e*=10);c=c.toISOString().slice(0,19).replace("T"," ")+"."+e;a.ct=c;a.t=b.v;window.location.host&&(a.ph=window.location.host);a.pq=window.location.pathname+window.location.search;navigator.sendBeacon?navigator.sendBeacon(b.i,p(a)):t(a,d,!0)}function C(a){var d=b.B,c;window.XMLHttpRequest?c=new XMLHttpRequest:c=new ActiveXObject("Microsoft.XMLHTTP");c.onreadystatechange=function(){4==c.readyState&&200==c.status&&"function"===typeof a&&
a(c)};c.open("POST",d+"/ajax.php",!0);c.setRequestHeader("Content-type","application/x-www-form-urlencoded; charset=UTF-8");c.send("a=sc")}function m(a){return D(function(d){return a===d})}function D(a){if(document.cookie&&""!=document.cookie)for(var d=document.cookie.split(";"),c=0;c<d.length;c++){var b=d[c].split("=");b[0]=b[0].replace(/^ /,"");var f=decodeURIComponent(b[1]);if(a(decodeURIComponent(b[0]),f))return f}}function u(a){var b=[];if(document.cookie&&""!=document.cookie)for(var c=document.cookie.split(";"),
e=0;e<c.length;e++){var f=c[e].split("=");if(f&&2==f.length){var g=f[0];f[0]=decodeURIComponent(g.replace(/^ /,""));if(a(f[0])){var k=f[1],h=decodeURIComponent(k);if(null!=h&&0<h.length){var h=h.split(":"),l=f[0].indexOf("_r_");if(-1<l&&h&&2<=h.length){var m=0;2<h.length&&h[2]&&(m=Number(h[2]));f={name:f[0],uid:h[0],H:h[1],o:f[0].substring(l+3),creationTime:m,A:0<=f[0].indexOf("ajax"),f:g,C:k};3<h.length&&h[3]&&(f.s=h[3]);b.push(f)}}}}}return b}function E(a){var b=new Date;b.setTime(b.getTime()+864E5);
document.cookie="sbs_cookie_lock="+a+";"+(" expires="+b.toUTCString()+";")+" path=/"}function n(a){document.cookie=a+"="+m(a)+";expires=Thu, 01 Jan 1970 00:00:01 GMT; path=/"}function F(a){for(var d=0;d<a.length;d++){var c=a[d];if(5E4<(new Date).getTime()+b.j-c.creationTime)n(c.f);else if(!c.s){c.A?n(c.f):document.cookie=c.f+"="+c.C+":"+b.h+";;path=/";var e={};e.r=c.o;e.u=c.uid;q(e,"trackPageView")}}}function v(a){var d={};d.hu=a;b.c&&(d.firewall_action=b.c);q(d,r)}function w(){if(b&&!b.D&&(b.D=!0,
clearInterval(b.w),clearInterval(b.G),b.m&&n("sbs_cookie_lock"),!navigator.sendBeacon&&b.b&&0<Object.keys(b.b).length))for(var a in b.b)if(b.b.hasOwnProperty(a)){var d=b.b[a];t(d,d.a,!1)}}function x(){var a=m("sbs_cookie_lock"),d="",c=null;"undefined"!==typeof a&&(a=a.split(":"),2==a.length&&(c=a[0],d=Number(a[1])));var e=(new Date).getTime();"undefined"===typeof a||c==b.h||e>d?(E(b.h+":"+((new Date(e)).getTime()+y+2E3)),b.m=!0,a=u(function(a){return 0==a.indexOf("sbs_ajax_r_")||0==a.indexOf("sbs_r_")}),
"undefined"!==typeof a&&F(a)):b.m=!1}var B=(new Date).getTime(),A=0;if("undefined"!==typeof initial_sbs_data){window.addEventListener("beforeunload",function(){w()});window.addEventListener("unload",function(){w()});var b={uniqueID:initial_sbs_data.uniqueID,g:initial_sbs_data.requestID,v:initial_sbs_data.clientToken,i:initial_sbs_data.apiURL,B:initial_sbs_data.pluginURL,b:{},j:0};initial_sbs_data.firewallAction&&(b.c=initial_sbs_data.firewallAction);b.l=!0;var z="sbs_r_"+b.g,k=u(function(a){return a==
z}),l=null;0<k.length&&(l=k[0]);l&&l.uid==b.uniqueID&&l.o==b.g&&(n(z),b.l=!1,b.j=(new Date).getTime()-l.creationTime,l.s||(k={},k.r=b.g,k.u=b.uniqueID,b.c&&(k.firewall_action=b.c),q(k,r)));b.l&&((k=m("sbs_huid"))?v(k):C(function(){var a=m("sbs_huid");a&&v(a)}));b.h=Math.random().toString(36).substr(2,16);var y=3E3;x();b.w=setInterval(x,y)}})([],"trackPageView");Date.now||(Date.now=function(){return(new Date).getTime()});
