<div class="terms-container">
    <p><b>Website Terms of Usage</b></p>
    <p>By accessing this website, you agree that your access to, and use of the website will be subject to the conditions set forth in these Terms of Use and all applicable laws. If you do not agree and accept, without limitation or qualification, these terms, please exit the website.</p>
    <p>This website and all of its content, including, but not limited to, all text, graphics, logos, button icons, images, and software belongs to Sabres Security, Inc. The design and layout of this website is the exclusive property of Sabres Security, Inc. and may not be used, copied, distributed or displayed in any way. Sabres Security® is a registered trademark of Sabres security ltd. All other registered trademarks and/or trademarks are the property of their respective owners. This website may contain proprietary notices and copyright information, the terms of which must be observed and followed.</p>
    <p>Sabres Security, Inc. Inc. grants you a limited license to make personal use of the website. Except as noted, you are not conveyed any right or license by implication, estoppel, or otherwise, to use, reproduce, transmit, perform, publish, modify, rewrite, create derivative works from, transfer or sell any content or information contained within this website, including but not limited to any of Sabres Security, Inc.’s intellectual property.</p>
    <p>Your limited license to use does not include, without limitation: (a) any resale or commercial use of the website or content therein; (b) the collection and use of any product listings or descriptions; (c) making derivative use of the website and its contents; and (d) use of any data mining, robots, or similar data gathering and extraction methods. You may not use, frame, or utilize framing techniques to enclose any Sabres Security, Inc. trademark, logo or other proprietary information (including the images found at this website, the content of any text or the layout/design of any page or form contained on a page) without Sabres Security, Inc.’s express written consent. Further, you may not use any meta tags or any other “hidden text” utilizing any Sabres Security, Inc.’s name, trademarks, or product names without Sabres Security, Inc. express written consent.</p>
    <p>No images on this website may be used without first seeking Sabres Security, Inc. express permission. To request permission to use Sabres Security, Inc.’s intellectual property, email Sabres Security, Inc. at <a href="mailto:contact@sabressecurity.com">contact@sabressecurity.com</a>. Sabres Security, Inc. reserves the right to refuse any permission request for any reason.</p>
    <p>Any unauthorized use of this website will immediately terminate the limited license and/or rights granted herein. Unauthorized uses of Sabres Security, Inc. intellectual property may violate applicable laws including copyright laws, trademark laws (including trade dress), and communications regulations and statutes. All violators will be prosecuted to the fullest extent of the law, including the seeking of criminal prosecution when warranted.</p>
    <p><b>Changes / Accuracy of Information</b></p>
    <p>Information may be changed or updated without notice. Sabres Security, Inc. may also make improvements and/or changes in the products and/or programs described in this information at any time without notice.</p>
    <p>Sabres Security, Inc. assumes no responsibility regarding the accuracy of the information that is provided by this website and use of such information is at the recipient’s own risk. Information on this website may contain technical inaccuracies or typographical errors and may not be complete. Please note that such errors or inaccuracies or omissions may relate to the pricing of items available for purchase on this website. Sabres Security, Inc. reserves the right to cancel or refuse to accept any order placed for any reason. Prices and availability are subject to change without notice. Sabres Security, Inc. apologizes for any inconvenience. Reference should be made to program documents for precise terms and conditions.</p>
    <p><b>Global Availability</b></p>
    <p>Information Sabres Security, Inc. publishes on the World Wide Web may contain references or cross references to Sabres Security, Inc. products, programs and services that are not announced or available in your country, state or municipality. Such references do not imply that Sabres Security, Inc. intends to announce such products, programs or services in your country, state or municipality. Consult your local Sabres Security, Inc. business contact for information regarding the products, programs and services that may be available to you.</p>
    <p>Sabres Security, Inc.’s obligations with respect to its products and services are governed solely by the agreements under which they are provided. If you obtain a product or service from Sabres Security, Inc. off this website that is provided without an agreement, that product or service is provided “as-is” with no warranties whatsoever, express or implied, and your use of that product or service is at your own risk.</p>
    <p><b>Links</b></p>
    <p>Sabres Security, Inc. makes no representations whatsoever about any other website which you may access through this one. When you access a non-Sabres Security, Inc. website, even one that may contain the Sabres Security, Inc. logo, please understand that it is independent from Sabres Security, Inc., and that Sabres Security, Inc. has no control over the content on that website. In addition, a link to a non-Sabres Security, Inc. website does not mean that Sabres Security, Inc. endorses or accepts any responsibility for the content, privacy policies, security or the use of such a website. It is up to you to take precautions to ensure that your use is free of such items as viruses, worms, Trojan horses and other items of a destructive nature.</p>
    <p><b>Disclaimer of Warranties</b></p>
    <p>All information is provided by Sabres Security, Inc. on an “as-is” basis only unless otherwise stated. Sabres Security, Inc. provides no representations and warranties, express or implied, including the implied warranties of fitness for a particular purpose, merchantability and non-infringement.</p>
    <p><b>Exclusion of liability</b></p>
    <p>Your use of the website and any of its content or features is at your own risk. In no event will Sabres Security, Inc. nor any of its subsidiaries, affiliates, officers, directors, agents, contractors, representatives, employees, successors, or assigns, or any other party involved in creating, producing, or delivering this website, be liable to any party for any direct, indirect, punitive, incidental, special or other consequential damages for any use of this web website or content, or on any other hyper-linked web website, including, without limitation, any lost profits, business interruption, loss of programs or other data on your information handling systems or otherwise, even if we are expressly advised of the possibility of such damages. Because some states do not allow the limitation or exclusion of liability for consequential or incidental damages, the above limitation may not apply to you.</p>
    <p><b>Law and Jurisdiction</b></p>
    <p>This Legal Statement and your use of the website are governed by the laws of the State of New York without regard to its choice of law provisions. The courts of general jurisdiction located within the State of New York shall have exclusive jurisdiction over any and all disputes arising out of, relating to, or concerning this Legal Statement and/or the website or in which this Legal Statement and/or the website are a material fact.</p>
    <p><b>General</b></p>
    <p>This Legal Statement may not be modified except in writing. If any of these terms shall be deemed unlawful, void, or for any reason unenforceable, that provision shall be severed from these terms and shall not affect the validity and enforceability of the remaining provisions.</p>
</div>
